name 'kreczko-site'
version '0.1.3'

author 'kreczko'
license 'Apache License, Version 2.0'
project_page 'https://github.com/uobdic/dice_T2_puppet_config'
source 'git@github.com:uobdic/dice_T2_puppet_config.git'
summary 'Puppet configuration for DICE and T2 clusters'
description 'Puppet configuration for DICE and T2 clusters'
dependency 'kreczko/motd', '>=0.1.4'
dependency 'traylenator/cvmfs', '>=0.0.2'
dependency 'kreczko/yumhelper', '>=0.0.1'
dependency 'kreczko/apelpublisher', '>=0.0.1'
